import { Permission } from '@school-cms/common';
import {
  LayoutDashboard,
  Users,
  UserCheck,
  CalendarCheck,
  CreditCard,
  GraduationCap,
  Contact,
  FileSpreadsheet,
  Cpu,
  ShieldAlert,
  Settings,
  UserPlus,
  FileUp,
  ArrowRightLeft,
  CalendarDays,
  FileText,
  DollarSign,
  Receipt,
  Percent,
  TrendingUp,
  TrendingDown,
  AlertCircle,
  FileCheck,
  Printer,
  Sparkles,
  MessageSquare,
  Mail,
  Smartphone,
  Fingerprint,
  History,
  Shield,
  Layers,
  Award,
  Palette,
  SlidersHorizontal,
} from 'lucide-react';

export interface NavigationItem {
  id: string;
  label: string;
  href?: string;
  icon?: any;
  permission?: Permission;
  children?: NavigationItem[];
  badge?: string;
}

export const navigationConfig: NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
  },
  {
    id: 'students',
    label: 'Student Management',
    icon: Users,
    permission: Permission.STUDENTS_VIEW,
    children: [
      {
        id: 'students-add',
        label: 'Add Student',
        href: '/students?tab=add',
        icon: UserPlus,
        permission: Permission.STUDENTS_CREATE,
      },
      {
        id: 'students-directory',
        label: 'Student Directory',
        href: '/students',
        icon: Users,
        permission: Permission.STUDENTS_VIEW,
      },
      {
        id: 'students-import',
        label: 'Bulk Import Students',
        href: '/students?tab=import',
        icon: FileUp,
        permission: Permission.STUDENTS_CREATE,
      },
      {
        id: 'students-promotion',
        label: 'Student Promotion',
        href: '/students?tab=promotion',
        icon: Sparkles,
        permission: Permission.STUDENTS_EDIT,
      },
      {
        id: 'students-transfer',
        label: 'Class / Section Transfer',
        href: '/students?tab=transfer',
        icon: ArrowRightLeft,
        permission: Permission.STUDENTS_EDIT,
      },
    ],
  },
  {
    id: 'staff',
    label: 'Staff Management',
    icon: UserCheck,
    permission: Permission.STAFF_VIEW,
    children: [
      {
        id: 'staff-add',
        label: 'Add Staff',
        href: '/staff?tab=add',
        icon: UserPlus,
        permission: Permission.STAFF_MANAGE,
      },
      {
        id: 'staff-directory',
        label: 'Staff Directory',
        href: '/staff',
        icon: UserCheck,
        permission: Permission.STAFF_VIEW,
      },
      {
        id: 'staff-profiles',
        label: 'Staff Profiles',
        href: '/staff?tab=profiles',
        icon: FileText,
        permission: Permission.STAFF_VIEW,
      },
    ],
  },
  {
    id: 'attendance',
    label: 'Attendance',
    icon: CalendarCheck,
    permission: Permission.ATTENDANCE_VIEW,
    children: [
      {
        id: 'attendance-student',
        label: 'Mark Student Attendance',
        href: '/attendance',
        icon: CalendarCheck,
        permission: Permission.ATTENDANCE_MARK,
      },
      {
        id: 'attendance-staff',
        label: 'Staff Attendance',
        href: '/attendance?type=staff',
        icon: UserCheck,
        permission: Permission.ATTENDANCE_MARK,
      },
      {
        id: 'attendance-history',
        label: 'Attendance History',
        href: '/attendance?tab=history',
        icon: History,
        permission: Permission.ATTENDANCE_VIEW,
      },
      {
        id: 'attendance-holidays',
        label: 'Holidays & Leave',
        href: '/attendance?tab=holidays',
        icon: CalendarDays,
        permission: Permission.ATTENDANCE_VIEW,
      },
      {
        id: 'attendance-reports',
        label: 'Attendance Reports',
        href: '/reports?type=attendance',
        icon: FileText,
        permission: Permission.REPORTS_VIEW,
      },
    ],
  },
  {
    id: 'finance',
    label: 'Fees & Finance',
    icon: CreditCard,
    permission: Permission.FEES_VIEW,
    children: [
      {
        id: 'finance-dashboard',
        label: 'Finance Dashboard',
        href: '/finance',
        icon: CreditCard,
        permission: Permission.FEES_VIEW,
      },
      {
        id: 'finance-structure',
        label: 'Fee Structure',
        href: '/finance?tab=structure',
        icon: Layers,
        permission: Permission.FEES_VIEW,
      },
      {
        id: 'finance-generate',
        label: 'Generate Fees',
        href: '/finance?tab=generate',
        icon: Sparkles,
        permission: Permission.FEES_VIEW,
      },
      {
        id: 'finance-payment',
        label: 'Receive Payment',
        href: '/finance?tab=payment',
        icon: DollarSign,
        permission: Permission.FEES_RECEIVE,
      },
      {
        id: 'finance-ledger',
        label: 'Student Ledger',
        href: '/finance?tab=ledger',
        icon: Receipt,
        permission: Permission.FEES_VIEW,
      },
      {
        id: 'finance-discounts',
        label: 'Discounts / Concessions',
        href: '/finance?tab=discounts',
        icon: Percent,
        permission: Permission.FEES_ADJUST,
      },
      {
        id: 'finance-income',
        label: 'Income',
        href: '/finance?tab=income',
        icon: TrendingUp,
        permission: Permission.FINANCE_VIEW,
      },
      {
        id: 'finance-expenses',
        label: 'Expenses',
        href: '/finance?tab=expenses',
        icon: TrendingDown,
        permission: Permission.FINANCE_VIEW,
      },
      {
        id: 'finance-outstanding',
        label: 'Outstanding Fees',
        href: '/finance?tab=outstanding',
        icon: AlertCircle,
        permission: Permission.FEES_VIEW,
      },
    ],
  },
  {
    id: 'exams',
    label: 'Exams & Results',
    icon: GraduationCap,
    permission: Permission.EXAMS_MANAGE,
    children: [
      {
        id: 'exams-list',
        label: 'Exams',
        href: '/exams',
        icon: GraduationCap,
        permission: Permission.EXAMS_MANAGE,
      },
      {
        id: 'exams-schedule',
        label: 'Exam Schedule',
        href: '/exams?tab=schedule',
        icon: CalendarDays,
        permission: Permission.EXAMS_MANAGE,
      },
      {
        id: 'exams-marks',
        label: 'Marks Entry',
        href: '/exams?tab=marks',
        icon: FileSpreadsheet,
        permission: Permission.MARKS_ENTER,
      },
      {
        id: 'exams-processing',
        label: 'Result Processing',
        href: '/exams?tab=processing',
        icon: Sparkles,
        permission: Permission.RESULTS_PUBLISH,
      },
      {
        id: 'exams-published',
        label: 'Published Results',
        href: '/exams?tab=published',
        icon: FileCheck,
        permission: Permission.RESULTS_PUBLISH,
      },
      {
        id: 'exams-report-cards',
        label: 'Report Cards',
        href: '/exams?tab=report-cards',
        icon: Printer,
        permission: Permission.EXAMS_MANAGE,
      },
    ],
  },
  {
    id: 'id-cards',
    label: 'ID Cards',
    icon: Contact,
    permission: Permission.STUDENTS_VIEW,
    children: [
      {
        id: 'id-cards-students',
        label: 'Student ID Cards',
        href: '/id-cards?type=student',
        icon: Users,
        permission: Permission.STUDENTS_VIEW,
      },
      {
        id: 'id-cards-staff',
        label: 'Staff ID Cards',
        href: '/id-cards?type=staff',
        icon: UserCheck,
        permission: Permission.STAFF_VIEW,
      },
      {
        id: 'id-cards-templates',
        label: 'ID Card Templates',
        href: '/id-cards?tab=templates',
        icon: Palette,
        permission: Permission.SETTINGS_MANAGE,
      },
    ],
  },
  {
    id: 'reports',
    label: 'Reports',
    icon: FileSpreadsheet,
    permission: Permission.REPORTS_VIEW,
    children: [
      {
        id: 'reports-student',
        label: 'Student Reports',
        href: '/reports?type=students',
        icon: Users,
        permission: Permission.REPORTS_VIEW,
      },
      {
        id: 'reports-staff',
        label: 'Staff Reports',
        href: '/reports?type=staff',
        icon: UserCheck,
        permission: Permission.REPORTS_VIEW,
      },
      {
        id: 'reports-attendance',
        label: 'Attendance Reports',
        href: '/reports?type=attendance',
        icon: CalendarCheck,
        permission: Permission.REPORTS_VIEW,
      },
      {
        id: 'reports-fee',
        label: 'Fee Reports',
        href: '/reports?type=fees',
        icon: CreditCard,
        permission: Permission.REPORTS_VIEW,
      },
      {
        id: 'reports-finance',
        label: 'Finance Reports',
        href: '/reports?type=finance',
        icon: TrendingUp,
        permission: Permission.REPORTS_VIEW,
      },
      {
        id: 'reports-exam',
        label: 'Exam & Result Reports',
        href: '/reports?type=exams',
        icon: GraduationCap,
        permission: Permission.REPORTS_VIEW,
      },
    ],
  },
  {
    id: 'integrations',
    label: 'Integrations',
    icon: Cpu,
    permission: Permission.INTEGRATIONS_MANAGE,
    children: [
      {
        id: 'integrations-whatsapp',
        label: 'WhatsApp',
        href: '/integrations?type=whatsapp',
        icon: MessageSquare,
        permission: Permission.INTEGRATIONS_MANAGE,
      },
      {
        id: 'integrations-sms',
        label: 'SMS',
        href: '/integrations?type=sms',
        icon: Smartphone,
        permission: Permission.INTEGRATIONS_MANAGE,
      },
      {
        id: 'integrations-email',
        label: 'Email',
        href: '/integrations?type=email',
        icon: Mail,
        permission: Permission.INTEGRATIONS_MANAGE,
      },
      {
        id: 'integrations-biometric',
        label: 'Biometric Devices',
        href: '/integrations?type=biometric',
        icon: Fingerprint,
        permission: Permission.INTEGRATIONS_MANAGE,
      },
      {
        id: 'integrations-logs',
        label: 'Integration Logs',
        href: '/integrations?tab=logs',
        icon: History,
        permission: Permission.INTEGRATIONS_MANAGE,
      },
    ],
  },
  {
    id: 'roles',
    label: 'Roles & Permissions',
    icon: ShieldAlert,
    permission: Permission.ROLES_MANAGE,
    children: [
      {
        id: 'roles-users',
        label: 'Users',
        href: '/roles?tab=users',
        icon: Users,
        permission: Permission.USERS_MANAGE,
      },
      {
        id: 'roles-list',
        label: 'Roles',
        href: '/roles',
        icon: Shield,
        permission: Permission.ROLES_MANAGE,
      },
      {
        id: 'roles-matrix',
        label: 'Permission Matrix',
        href: '/roles?tab=matrix',
        icon: ShieldAlert,
        permission: Permission.ROLES_MANAGE,
      },
      {
        id: 'roles-audit',
        label: 'Audit Logs',
        href: '/roles?tab=audit',
        icon: History,
        permission: Permission.AUDIT_VIEW,
      },
    ],
  },
  {
    id: 'settings',
    label: 'Institute Settings',
    icon: Settings,
    permission: Permission.SETTINGS_MANAGE,
    children: [
      {
        id: 'settings-profile',
        label: 'Institute Profile',
        href: '/settings?tab=profile',
        icon: Settings,
        permission: Permission.SETTINGS_MANAGE,
      },
      {
        id: 'settings-branding',
        label: 'Branding',
        href: '/settings?tab=branding',
        icon: Palette,
        permission: Permission.SETTINGS_MANAGE,
      },
      {
        id: 'academic-setup',
        label: 'Academic Setup',
        icon: Layers,
        permission: Permission.SETTINGS_MANAGE,
        children: [
          {
            id: 'academic-sessions',
            label: 'Academic Sessions',
            href: '/settings?tab=sessions',
            icon: CalendarDays,
            permission: Permission.SETTINGS_MANAGE,
          },
          {
            id: 'academic-classes',
            label: 'Classes',
            href: '/settings?tab=classes',
            icon: Layers,
            permission: Permission.SETTINGS_MANAGE,
          },
          {
            id: 'academic-sections',
            label: 'Sections',
            href: '/settings?tab=sections',
            icon: Layers,
            permission: Permission.SETTINGS_MANAGE,
          },
          {
            id: 'academic-subjects',
            label: 'Subjects',
            href: '/settings?tab=subjects',
            icon: FileText,
            permission: Permission.SETTINGS_MANAGE,
          },
          {
            id: 'academic-grading',
            label: 'Grading System',
            href: '/settings?tab=grading',
            icon: Award,
            permission: Permission.SETTINGS_MANAGE,
          },
        ],
      },
      {
        id: 'settings-fees',
        label: 'Fee Settings',
        href: '/settings?tab=fees',
        icon: CreditCard,
        permission: Permission.SETTINGS_MANAGE,
      },
      {
        id: 'settings-attendance',
        label: 'Attendance Settings',
        href: '/settings?tab=attendance',
        icon: CalendarCheck,
        permission: Permission.SETTINGS_MANAGE,
      },
      {
        id: 'settings-exams',
        label: 'Exam Settings',
        href: '/settings?tab=exams',
        icon: GraduationCap,
        permission: Permission.SETTINGS_MANAGE,
      },
      {
        id: 'settings-general',
        label: 'General Settings',
        href: '/settings?tab=general',
        icon: SlidersHorizontal,
        permission: Permission.SETTINGS_MANAGE,
      },
    ],
  },
];
